[book]
authors = ["Servicenetzwerk Freie Bildung"]
description = "Handbuch"
language = "de"
src = "src"
title = "Servicenetzwerk Freie Bildung"

[build]
create-missing = false

[output.html]
fold.enable = true
fold.level = 0
input-404 = "book-assets/404.md"

